import UserBase from "./UserBase.js";
import mongoose from "mongoose";

const CandidateSchema = new mongoose.Schema(
  {
    lookingFor: { type: String, default: "" },
    choosingFor: { type: String, default: "" },
    addressInShort: { type: String, default: "" },
    currentAddress: { type: String, default: "" },
    isVerified: { type: Boolean, default: false },
    community:{type:String,default:""},
    isPhoneVerified: { type: Boolean, default: false },
    isEmailVerified: { type: Boolean, default: false },
    image: { type: Array, default: [] },
    images: { type: Array, default: [] },
    birthDate: { type: Date, default: null },
    birthTime: { type: String, default: "" },
    age: { type: String, default: "" },
    birthPlace: { type: String, default: "" },
    height: { type: String, default: "" },
    bloodGroup: { type: String, default: "" },
    disabilityYN: { type: String, default: "No" },
    disablityDescription: { type: String, default: "" },
    degreeDiploma: { type: String, default: "" },
    degreeName: { type: String, default: "" },
    fieldJob: { type: String, default: "" },
    companyName: { type: String, default: "" },
    jobBusiness: { type: String, default: "" },
    incomeGroup: { type: String, default: "" },
    eatingHabits: { type: String, default: "" },
    raas: { type: String, default: "" },
    gotra: { type: String, default: "" },
    dosha: { type: String, default: "" },
    gana: { type: String, default: "" },
    devak: { type: String, default: "" },
    nakshatra: { type: String, default: "" },
    charan: { type: String, default: "" },
    naadi: { type: String, default: "" },
    familyType: { type: String, default: "" },
    siblingCount: { type: String, default: "" },
    educationOfSiblings: { type: String, default: "" },
    property: { type: String, default: "" },
    educationOfMother: { type: String, default: "" },
    educationOfFather: { type: String, default: "" },
    motherFamilyDetails: { type: String, default: "" },
    fatherFamilyDetails: { type: String, default: "" },
    expectedEducations: { type: Array, default: [] },
    expectedIncome: { type: Array, default: [] },
    expectedEatingHabits: { type: Array, default: [] },
    expectedGana: { type: Array, default: [] },
    expectedNakshatra: { type: Array, default: [] },
    expectedAgeGapMin: { type: String, default: "" },
    expectedAgeGapMax: { type: String, default: "" },
    expectedBloodGroups: { type: Array, default: [] },
    expectedNaadi: { type: Array, default: [] },
    expectedRaas: { type: Array, default: [] },
    expectedHeight: { type: String, default: "" },
    expectedFamilyType: { type: Array, default: [] },
    expectedSiblingsCousinsUpto: { type: Number },
    profileWithImages: { type: Boolean, default: true },
    strictMatch: { type: Boolean, default: true },
    userPaid: { type: Boolean, default: false },
    readTCP: { type: Boolean, default: true }
  },
  { _id: false }
);

const Candidate = UserBase.discriminator("candidate", CandidateSchema);

export default Candidate;
